name: Go Tests

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.x
            - name: Run tests
              run: |
                  for dir in $(find . -type d -not -path "./.git*" -not -path "./vendor*"); do
                    if ls $dir/*.go &> /dev/null; then
                      echo "Running tests in $dir"
                      go test -v -coverprofile=coverage.out $dir
                    fi
                  done
            - name: Upload test coverage
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: coverage
                  path: coverage.out
